version: '3.7'

services:
    mariadb:
        image: docker.io/bitnami/mariadb:latest
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            #- ALLOW_EMPTY_PASSWORD=yes
            - MARIADB_USER=web
            - MARIADB_DATABASE=web
            - MARIADB_ROOT_PASSWORD=web
            - MARIADB_PASSWORD=web
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb:/bitnami/mariadb/data
    app:
        build:
            dockerfile: Dockerfile
        image: docker.io/bitnami/laravel:latest
        ports:
            - '8000:80'
        environment:
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_USERNAME=web
            - DB_DATABASE=web
            - DB_PASSWORD=web
        volumes:
            - ./project:/app
        depends_on:
            - mariadb