version: '3.7'

services:
    mariadb:
        image: docker.io/bitnami/mariadb:latest
        environment:
            - MARIADB_USER=web
            - MARIADB_DATABASE=web
            - MARIADB_ROOT_PASSWORD=web
            - MARIADB_PASSWORD=web
        ports:
            - "3306:3306"
#        volumes:
#            - ./mariadb:/bitnami/mariadb/data
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: docker.io/bitnami/laravel:latest
        ports:
            - '8000:8000'
        environment:
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_USERNAME=web
            - DB_DATABASE=web
            - DB_PASSWORD=web
        volumes:
            - ./project:/app
        depends_on:
            - mariadb
#        command: sh -c "cd /app/ && composer install && php artisan migrate:refresh --force && php artisan db:seed -force"
#        restart: "no"
#        entrypoint: sh -c "cd /app/ && sleep 30 && php artisan migrate:refresh --seed -force"